#!/usr/bin/sh
## Sets the display brightness to match battery level

if ! command -v light > /dev/null 2>&1 ; then
    echo "This script requires /usr/bin/light....Please install light and try again"
    exit 2
fi

battery_percentage=$(cat /sys/class/power_supply/BAT0/capacity)
set_percentage=$(bc <<< $battery_percentage/1.5)
battery_state=$(cat /sys/class/power_supply/BAT0/status)

if [[ $battery_state == "Charging" ]]; then
    light -S 100
else
    if [[  $battery_percentage == "100" ]]; then
        light -S 100
    else
        light -S $set_percentage
    fi
fi
