#!/bin/zsh
## Script to push all my git repos at the same time

#repos=$(/usr/bin/ls $HOME/Git)

if [[ $(ssh-add -l) == 0 ]]; then
    ssh-add
fi

#for i in "${repos}"; do
for i in "$HOME/Git"/*; do
    cd "$i"
    git pull

    for file in $(git ls-files --others --exclude-standard); do
        git add $file
        git commit -vS $file
    done

    for file in $(git diff --name-only); do
        git add -p $file
        git commit -vS $file
    done

    git push
done

