#!/bin/sh
#Checks how much is being downloaded to calc a speed

red='#65350'
green='#99c76c'
yellow='#ffc24b'
blue='#268bd2'
magenta='#cd00cd'
cyan='#73cef4'

while true; do
    down_past=$(awk '{for(i=3;i<=NR;i++) t+=$2 } { print t }' /proc/net/dev | tail -n1)
    up_past=$(awk '{for(i=3;i<=NR;i++) t+=$10 } { print t }' /proc/net/dev | tail -n1)
    sleep 2
    down_now=$(awk '{for(i=3;i<=NR;i++) t+=$2 } { print t }' /proc/net/dev | tail -n1)
    up_now=$(awk '{for(i=3;i<=NR;i++) t+=$10 } { print t }' /proc/net/dev | tail -n1)

    #Prints out the digit padded to length 4
    #Divides by 2000 since 2000 bytes in a kilobyte, and divides by 2 since the sum includes lo and wlp0s29u1u5, where lo is this session, and wlp is a running total, so each byte is counted twice
    down_per_sec=$(awk -v n=$down_now -v p=$down_past 'BEGIN { printf "Down: %4d kB/s",(n-p)/(2048*2) }')
    up_per_sec=$(awk -v n=$up_now -v p=$up_past 'BEGIN { printf "up: %4d kB/s",(n-p)/(2048*2) }')

    echo "%{u$blue}$down_per_sec""%{-u} | ""%{u$blue}$up_per_sec"
done
