#!/bin/sh
# Checks how many packages need updating

red='#65350'
blue='#268bd2'

echo "Refreshing..."

#Need to update or it wont know there are new packages
pikaur -Sy > /dev/null 2>&1

pac=$(pacman -Qqu 2> /dev/null | wc -l)
aur=$(pikaur -Qqu 2> /dev/null | wc -l)
aur=$(awk -v a='$aur' -v p='$pac' 'BEGIN { printf a+b }')

[ "$pac" = "0" ] && [ "$aur" = "0" ] && colour=$blue || colour=$red
echo "%{u$colour}$pac  $aur"
