#!/bin/sh
# ust prints memory I have available to use in polybar

while true; do
    free_mem=$(free | awk 'NR==2{ print $7 }')
    tot_mem=$(free | awk 'NR==2{ print $2 }')
    free_percentage=$(awk -v f=$free_mem -v t=$tot_mem 'BEGIN { printf "%1d",100*(1-(f/t)) }')

    if [ $free_percentage -gt 90 ]; then
        echo "%{u#e65350} $free_percentage%"
    elif [ $free_percentage -gt 75 ]; then
        echo "%{u#e65350} $free_percentage%"
    elif [ $free_percentage -gt 50 ]; then
        echo "%{u#ffc24b} $free_percentage%"
    else
        echo "%{u#99c794} $free_percentage%"
    fi

    sleep 1
done
