#!/bin/zsh
# Use zsh so can use bash-isms
# Feed this script a link and it will give rofi list of link_handlers to open with

# The URL will be shown visually in 30 characters or less.
if [[ "${#1}" -gt 30 ]];
then
    visual="${1:0:20}"..."${1: -7}"
else
    visual="$1"
fi
echo $visual

link_handlers=$(printf "umpv\n\
mpv\n\
firefox\n\
feh\n\
paragraph\n\
summary\n\
ytdl\n\
speedread\n\
speedread_summary\n\
linkfile"\
| rofi -dmenu -i -mesg "How should I open '$visual'?" -select)

echo "$link_handlers"

case "$link_handlers" in
    umpv) "$HOME/git/scripts/shell/umpv" "$1" & ;;
    mpv) mpv --pause --ytdl-format="best[height<=720]" --quiet "$1" 2>/dev/null & ;;
    firefox) firefox "$1";;
    feh) feh --scale-down --recursive "$1" --title "%S %n";;
    paragraph) /bin/rm /tmp/para.txt && "$HOME/git/scripts/python/paragraphscraper/paragraph_scraper.py" --url "$1" && bspc rule -a \* -o state=floating && alacritty -e bat /tmp/para.txt ;;
    summary) /bin/rm /tmp/para.txt && "$HOME/git/scripts/python/paragraphscraper/paragraph_scraper.py" --url "$1" && "$HOME/git/scripts/python/paragraphscraper/article_summarise_cosine.py" --file-name /tmp/para.txt --context > /tmp/summary.txt && bspc rule -a \* -o state=floating && alacritty -e bat /tmp/summary.txt ;;
    ytdl) youtube-dl "$1" > /dev/null 2>&1 & ;;
    speedread) pass;;
    speedread_summary) pass;;
    linkfile) touch /tmp/linkfile.txt && echo "$1" >> /tmp/linkfile.txt ;;
    *) "$link_handlers" "$1";;
esac
