#!/bin/python
#Use this to rename my BSPWM workspaces to icons

import re
import subprocess

icons_dict = {
    "alacritty": str(""),
    "firefox": str(""),
    "mpv": str(""),
    "*": str("_"),
}

# Edit this with info from bspc query --desktops
desktops_dict = {
    "0x00400006": "1",
    "0x00400008": "2",
    "0x00400009": "3",
    "0x0040000A": "4",
    "0x0040000B": "5",
    "0x0040000C": "6",
    "0x00400007": "7",
    "0x0040000D": "8",
    "0x0040000E": "9",
    "0x0040000F": "10",
}

def check_desktop_classes(desktop):
    '''checks what windows are open on a desktop and adds them to a list'''
    my_cmd = f"bspc query --tree --desktop {desktop}"
    items = []
    raw_output = subprocess.Popen([my_cmd], stdout=subprocess.PIPE, shell=True).communicate()
    raw_output = str(raw_output)
    regexed_output = re.findall('"className":".*?"', raw_output)
    for item in regexed_output:
        #keep only text after :" and before "
        items.append(re.findall(':"(.*)"', item)[0])
    return items

def create_desktop_name(desktop):
    '''Loops over list of applications, and turns it into a string of icons'''
    desktop_name = ''
    output = check_desktop_classes(desktop)
    for item in output:
        for key in icons_dict:
            if item == key:
                desktop_name += f'{icons_dict[key]} '

    if desktop_name == '':
        desktop_name = desktops_dict[desktop]
    #else:
        #remove trailing whitespace
        #desktop_name = desktop_name[:-1]

    return desktop_name

def set_desktop_name(desktop):
    '''Runs bspc coommand to change desktop name'''
    desktop_name = create_desktop_name(desktop)
    my_cmd = f'bspc desktop {desktop} --rename "{desktop_name}"'
    subprocess.call([my_cmd], shell=True)

def rename_all_desktops():
    '''TODO: bspc subscribe node_{add,remove} | while read -r line; do; echo "Changed"; done'''
    '''Loops over desktops and renames all'''
    desktop_list = ["0x00400006", "0x00400008", "0x00400009", "0x0040000A", "0x0040000B", "0x00400007", "0x0040000C", "0x0040000D", "0x0040000E", "0x0040000F"]
    for desktop in desktop_list:
        set_desktop_name(desktop)

if __name__ == "__main__":
    rename_all_desktops()
